### ISSUE TITLE
v_opnvwk binding should not set default text size

### ISSUE THREAD

**Issue by czietz** [freemint/gemlib#11]
As discussed here https://github.com/freemint/freemint/issues/106, the v_opnwk binding should not set a default text size. I.e., the following line should be removed:
https://github.com/freemint/gemlib/blob/d57cebf1d47d9d16507c0530eed4665bcb6ea160/v_opnvwk.c#L47

Furthermore, it should be discussed whether v_opnwk should set _any_ defaults at all. Imho, a user expect the v_opnvwk binding to just call the corresponding VDI function, not a bunch of other functions, as well.

**Comment by th-otto** [comment]
Merged as #12. I left the other calls in for now, but maybe they should be removed, too. AFAIK there is nowhere documented what the default values are (the important ones are set by using intin[0..9] anyway), so relying on any particular setting is just bad practice.

**Comment by mikrosk** [comment]
Hmm, maybe @Landemarre or @arnaudbercegeay remember why it has been done like that?

**Comment by Landemarre** [comment]
Hello

I not write this, my point of view this is because some VDI not set 
correctly at start some parameters but my point of view value set should 
be a copy of current parameters of the handle put in control[6] not 
default value. In theory a software should in all case set this 
parameters by themself and should not have an issue with this, if not we 
can consider they are undefined so be a bug in software.

Olivier
