### ISSUE TITLE
make install and kernel32.slb

### ISSUE THREAD

**Issue by vinriviere** [freemint/gemlib#7]
`make install` tries to install the pre-built ./kernel32.slb. This is wrong as kernel32.slb has just been rebuilt elsewhere.

IMHO that ./kernel32.slb should definitely be removed from the gemma source tree.

**Comment by th-otto** [comment]
Oops, you are right. Fixed.

**Comment by vinriviere** [comment]
Still not good. All kernel32.slb multilibs should be installed, like gemma32.slb.

**Comment by th-otto** [comment]
We could do that, but remember that previously there also was also only one version of that library. And the library compiled for '000 is of course also valid for '020 and above. And if you look at there size, they differ only by 10 bytes, so you don't achieve much by using the '020 version.

Beside that, its only active user as for now is gemma itself, and that too is configured to not use it. The reason i did that, is that kernel32.slb is actually quite useless. Most of the time, the functions are just wrappers for the actual gemdos functions, and calling the library for it generates even more code than calling the gemdos function directly, because you also have to pass the library handle and the number of arguments.

**Comment by vinriviere** [comment]
Please install the 3 versions, or none at all. 680x0 versions can't run on plain ColdFire, that's the main point.

**Comment by th-otto** [comment]
Ok, done now.

**Comment by vinriviere** [comment]
Thanks, that looks fine, now.

**Comment by vinriviere** [comment]
Excellent, for the first time I have been able to build gemma's test program for ColdFire and run it successfully on FireBee/EmuTOS/FreeMiNT 😃
