### ISSUE TITLE
gemma dependency to gemlib internal symbols.h

### ISSUE THREAD

**Issue by vinriviere** [freemint/gemlib#8]
`gemma/kernel32/header.S` depends on `"symbols.h"` which is located inside gemlib's private sources. That's bad practice, that symbols.h should be moved to a central place such as MiNTLib.

**Comment by th-otto** [comment]
In general you are right. But it does not belong to mintlib either, since it then would have to be installed to public places, but is only needed for building the library. Actually there should be a copy of that file inside gemma, but i think we should wait with that until the library has been moved to its own repo.

**Comment by mikrosk** [comment]
Copied as @th-otto suggested.
