### ISSUE TITLE
gemma should not depend on ../../gemlib/gem.h

### ISSUE THREAD

**Issue by vinriviere** [freemint/gemlib#9]
Seen in `gemma/kernel32/kernel32.h` and `gemma/src/gemma.h`:
`#include "../../gemlib/gem.h"`

This is not good, because even if currently gemlib and gemma are inside the same Git repository, this should not be a requirement. Ideally, gemlib and gemma should have their own repository, and gemma should have a dependency to gemlib. So gemma could be independant, and just do `#include <gem.h>` like any other program.

**Comment by th-otto** [comment]
You are right, but this cannot be fixed until the repos are split. As long as gemlib is part of the same repo, you cannot assume that #include <gem.h> works when compiling gemma. Btw the code before by changes to gemma.h was

```
#include "/usr/GEM/include/gem.h"
```

which did not work very well, because gemlib is not installed to /usr/GEM. Not to speak about cross-compilation.

**Comment by mikrosk** [comment]
Doesn't anymore.
